### PR TITLE
feat: modify case-sensitive URLs

### LINKED ISSUE #713: Need to modify case-sensitive URLs
**Actual Behaviour**

 

Currently, the URLs on blogs are case-sensitive, which is resulted from rules set by Apache Server. The case-sensitive URLs become inconvenient when referencing them in other websites and social media. Some might change the upper-case letters in the URLs to lower-case letters automatically. Yet visiting the low-case URLs would return a 404 page.

From the user's aspect (i.e. anyone tries to visit the URLs for the first time) would not be able to access the contents in URLs. And the user experience can be improved.

**Expected Behaviour**

 

1. input the URLs with upper-case letters, it is accessible
2. input the URLs with lower-case letters, it is also accessible

**Steps to reproduce it**
Take https://apisix.apache.org/blog/2021/06/28/why-we-need-Apache-APISIX/ for example:

1. Open your browser.
2. Input the URL:https://apisix.apache.org/blog/2021/06/28/why-we-need-Apache-APISIX/
3. Access the content successfully.
4. Change `Apache-APISIX` to lower-case `apache-apisix`
5. Returns 404.

 

**Screenshots of the issue**
image
image

 

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by mangoGoForward**
Fixes: #713

Changes:

Use `slug` to customize the document url and unified with lower-case style.

Screenshots of the change:

image

### CODE REVIEW

**Comment by mangoGoForward** [comment]
Hi, @yzeng25 ,the step of ` Deploy Preview for apache-apisix` failed, and the [deploy log](https://app.netlify.com/sites/apache-apisix/deploys/62187026e1f93600073281ed) no more detail like the below screenshot.

image

I want to take a preview on netlify, please have a look, thanks.

**Comment by yzeng25** [comment]
> Hi, @yzeng25 ,the step of ` Deploy Preview for apache-apisix` failed, and the [deploy log](https://app.netlify.com/sites/apache-apisix/deploys/62187026e1f93600073281ed) no more detail like the below screenshot.
> 
> image
> 
> I want to take a preview on netlify, please have a look, thanks.
The Netlify checks failure is probably due to network issue. 
You can try  `git rebase -i HEAD~2` and `git push -f` again.

**Comment by yzeng25** [comment]
> Hi, @yzeng25 ,the step of ` Deploy Preview for apache-apisix` failed, and the [deploy log](https://app.netlify.com/sites/apache-apisix/deploys/62187026e1f93600073281ed) no more detail like the below screenshot.
> 
> image
> 
> I want to take a preview on netlify, please have a look, thanks.

The Netlify checks failure is probably due to network issue. 
You can try  `git rebase -i HEAD~2` and `git push -f` again.

**Comment by bzp2010** [comment]
I noticed in the build output that these "client redirects" require the presence of the target file to be valid, so we need to change the file name of the corresponding document to all lowcase.

```text
2:02:30 PM: Error: You are trying to create client-side redirections to paths that do not exist:
2:02:30 PM: - /blog/2021/06/28/why-we-need-apache-apisix
2:02:30 PM: - /blog/2021/10/26/apisix-ingress
2:02:30 PM: - /blog/2021/10/01/openeuler
2:02:30 PM: - /blog/2021/09/28/wps-usercase
2:02:30 PM: - /blog/2021/09/07/iqiyi-usercase
2:02:30 PM: - /blog/2021/09/06/python-helps-you-quickly-with-apache-apisix-development
2:02:30 PM: - /blog/2021/05/24/tencent-games
```

**Comment by mangoGoForward** [comment]
Hi, @yzeng25 ,seems [method 3](https://github.com/apache/apisix-website/issues/713#issuecomment-989535566) not a good solution, or I misunderstand?

**Comment by yzeng25** [comment]
> Hi, @yzeng25 ,seems [method 3](https://github.com/apache/apisix-website/issues/713#issuecomment-989535566) not a good solution, or I misunderstand?

Agree with you. Don't hesitate to provide other alternatives.

**Comment by mangoGoForward** [comment]
> Agree with you. Don't hesitate to provide other alternatives.

I have no good ideas, how about use `slug` as the [comment](https://github.com/apache/apisix-website/issues/713#issuecomment-989535566) said, and unified use lower-case style.

**Comment by yzeng25** [comment]
> > Agree with you. Don't hesitate to provide other alternatives.
> 
> I have no good ideas, how about use `slug` as the [comment](https://github.com/apache/apisix-website/issues/713#issuecomment-989535566) said, and unified use lower-case style.

Sounds good!

**Comment by mangoGoForward** [comment]
> > > Agree with you. Don't hesitate to provide other alternatives.
> > 
> > 
> > I have no good ideas, how about use `slug` as the [comment](https://github.com/apache/apisix-website/issues/713#issuecomment-989535566) said, and unified use lower-case style.
> 
> Sounds good!

Please have a review in commit [342fcb6](https://github.com/apache/apisix-website/pull/903/commits/342fcb6dd006251d48a264f54e73775e8dabc450)

**Review by yzeng25 — APPROVED** [review]

**Comment by yzeng25** [comment]
> > > > Agree with you. Don't hesitate to provide other alternatives.
> > > 
> > > 
> > > I have no good ideas, how about use `slug` as the [comment](https://github.com/apache/apisix-website/issues/713#issuecomment-989535566) said, and unified use lower-case style.
> > 
> > 
> > Sounds good!
> 
> Please have a review in commit [342fcb6](https://github.com/apache/apisix-website/pull/903/commits/342fcb6dd006251d48a264f54e73775e8dabc450)

Awesome!

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
