### PR TITLE
fix: change the download links for  hash and sig

### PR DESCRIPTION
**Pull request by gxthrj**
Related to apache/apisix-ingress-controller#146

### CODE REVIEW

**Comment by sebbASF** [comment]
Sorry, but it is still wrong.

The source file name is now
apache-apisix-ingress-controller-0.1.0-rc2-src.tar.gz

But the hash and sig are:
apache-apisix-ingress-controller-0.1.0-src.tar.gz.asc
apache-apisix-ingress-controller-0.1.0-src.tar.gz.sha512

The -rc2 should also be dropped from the source.

**Comment by juzhiyuan** [comment]
cc @gxthrj @moonming

**Comment by gxthrj** [comment]
> Sorry, but it is still wrong.
> 
> The source file name is now
> apache-apisix-ingress-controller-0.1.0-rc2-src.tar.gz
> 
> But the hash and sig are:
> apache-apisix-ingress-controller-0.1.0-src.tar.gz.asc
> apache-apisix-ingress-controller-0.1.0-src.tar.gz.sha512
> 
> The -rc2 should also be dropped from the source.

Fixed. @sebbASF  
If this is OK， I hope to merge this PR.
Happy New Year !

**Comment by sebbASF** [comment]
Looks better now, thanks

**Review by juzhiyuan — APPROVED** [review]

**Review by moonming — APPROVED** [review]

**Pull request merged**
