### PR TITLE
style: set max-width of doc container to avoid x-overflow

### LINKED ISSUE #288: bug: hidableSidebar does not behave correctly
**Actual Behaviour**

After I try to hide the sidebar, the page would move and I have to scroll to find where I just read.

Example: http://apisix.incubator.apache.org/docs/apisix/admin-api#service

**Expected Behaviour**

The page would not move, or the first line of the page would not change. And that's how doc of docusauras works so I think it's supported.

Example: https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima

**Steps to reproduce it**

Open a page, scroll down a bit, and hide the sidebar.

### PR DESCRIPTION
**Pull request by 1502shivam-singh**
Fixes: #288

Changes:

Previously (See the x-scroll bar due to overflow in document main container (.docMainContainer))

image

Screenshots of the change:

Later (After setting max-width of container)

image

### CODE REVIEW

**Comment by Yiyiyimu** [comment]
@1502shivam-singh maybe you need to rebase the branch

**Comment by 1502shivam-singh** [comment]
> @1502shivam-singh maybe you need to rebase the branch

Hmmm, feel you. Too much backlog here.

**Review by juzhiyuan — APPROVED** [review]
Yes, you should rebase codes.

**Comment by 1502shivam-singh** [comment]
I did the rebase, check if it's fine now.

**Comment by Yiyiyimu** [comment]
> I did the rebase, check if it's fine now.

try rebase master and it would need force push. there are still 10 commits right now

**Comment by juzhiyuan** [comment]
Hi @Yiyiyimu, maybe it's ok to merge? because this PR only contain the current changes, and we will use Squash to merge.

**Review by Yiyiyimu — APPROVED** [review]

**Comment by iamayushdas** [comment]
> I did the rebase, check if it's fine now.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
check the rebase part, i have also learned it from there only

**Review by iamayushdas — APPROVED** [review]

**Comment by 1502shivam-singh** [comment]
> Hi @Yiyiyimu, maybe it's ok to merge? because this PR only contain the current changes, and we will use Squash to merge.

I guess I should try for sometime. Been a little rusty with git, so need to check out something and then try.

Thanks @iamayushdas  will check the link you shared.

**Comment by 1502shivam-singh** [comment]
Squashed the commits, have a look guys.

**Comment by iamayushdas** [comment]
No bro, clean your history, see the active changes 3500+ active changes
Wait let me help you.

**Pull request closed without merging**
