### PR TITLE
docs: add lenovo-uses-apisix.md

### PR DESCRIPTION
**Pull request by Yilialinn**
Lenovo case study shared by Leon Yang

### CODE REVIEW

**Comment by yzeng25** [comment]
Just wondering if you could upload screenshot(s) of the article from local preview.

**Comment by Yilialinn** [comment]
> Just wondering if you could upload screenshot(s) of the article from local preview.

我没太明白，可以帮忙解释下不？这篇我还要继续改的～

**Comment by yzeng25** [comment]
> > Just wondering if you could upload screenshot(s) of the article from local preview.
> 
> 我没太明白，可以帮忙解释下不？这篇我还要继续改的～

- Please kindly mark this pull request as a draft before ready for reviews.
- Since the Netlify preview was removed, can you run local preview as described in  https://github.com/apache/apisix-website#building, and take some screenshots and upload them in the comment area of this pull request? 

Like: 
截屏2023-06-02 20 44 55

**Review by GeekEmily — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Comment by yzeng25** [comment]
Really? Please get online preview back to avoid similar problems in the future.

apisix apache org_blog_

**Pull request merged**
