### PR TITLE
style: unmount Contributor200Poster component

### LINKED ISSUE #443: style: Home page pop-ups removed
**Actual Behaviour**

image

**Expected Behaviour**

1. easy to reuse in the future, pull out as a component stand alone
2. Remove the style from the current home page

**Steps to reproduce it**

 

**Screenshots of the issue**

 

**Would you like to work on the issue?**

### PR DESCRIPTION
**Pull request by Baoyuantop**
Fixes: #443 

Changes:

Unmount `Contributor200Poster` component.

Screenshots of the change:

image

### CODE REVIEW

**Comment by Baoyuantop** [comment]
cc @guoqqqi

**Review by juzhiyuan — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

**Comment by guoqqqi** [comment]
wait for #447 update the Contributor200Poster link to this article

**Comment by 1502shivam-singh** [comment]
Hey @Baoyuantop, how about you refactor that theme based poster selection code using the useThemeContext[1] hook. No issues with the code at present, just that this would make it more compact.

[1] https://docusaurus.io/docs/api/themes/configuration#usethemecontext

**Comment by Baoyuantop** [comment]
> Hey @Baoyuantop, how about you refactor that theme based poster selection code using the useThemeContext[1] hook. No issues with the code at present, just that this would make it more compact.
> 
> [1] https://docusaurus.io/docs/api/themes/configuration#usethemecontext

Very good suggestion, thanks, I will revise it

**Review by bzp2010 — APPROVED** [review]

**Comment by Baoyuantop** [comment]
I just changed the content of the card and it looks like this now：

**light mode**

image

**dark mode**

image

Any good suggestions?

**Pull request merged**
