### PR TITLE
WIP: chore: add preview branch condition 

### PR DESCRIPTION
**Pull request by bzp2010**
Changes:

Add branch restrictions for PR preview push CI.

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Comment by bzp2010** [comment]
Update:
Currently, we can't get the token through GitHub secret. We're looking for infra's help.

**Comment by kezhenxu94** [comment]
> Update:
> Currently, we can't get the token through GitHub secret. We're looking for infra's help.

Secrets are not passed into the fork repo, I don’t think this GitHub action would work as expected.

**Comment by juzhiyuan** [comment]
> Secrets are not passed into the fork repo, I don’t think this GitHub action would work as expected.

Yes, Secrets are standalone, we could merge this first 🤔 to make it running as expected

**Comment by kezhenxu94** [comment]
> > Secrets are not passed into the fork repo, I don’t think this GitHub action would work as expected.
> 
> Yes, Secrets are standalone, we could merge this first 🤔 to make it running as expected

No. What I mean is that this GitHub Action will not work as expected. It aims at previewing the changes in pull requests, which are mostly opened from fork repos, that said, it mostly won’t be able to deploy a preview page due to the lack of privileges. .

**Pull request closed without merging**
