### PR TITLE
fix: add a bundle of good first issues links to homepage 

### LINKED ISSUE #178: Add a bundle of Good first issues links to Homepage
Add a bundle of Good first issues Section to the Homepage.

[1] https://github.com/apache/apisix#community

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Fixes: #178

Changes:

update homepage

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
LGTM, and needs @1502shivam-singh's review :)

image

**Review by moonming — APPROVED** [review]

**Comment by 1502shivam-singh** [comment]
> LGTM, and needs @1502shivam-singh's review :)
> 
> image

Just one minor thing can you make that GitHub logo png center aligned vertically with some padding like below -
image

**Comment by KishaniKandasamy** [comment]
> > LGTM, and needs @1502shivam-singh's review :)
> > image
> 
> Just one minor thing can you make that GitHub logo png center aligned vertically with some padding like below -
> image

yeah Sure

**Comment by juzhiyuan** [comment]
image

Hi, it looks like the icon is not aligned with text?

**Comment by juzhiyuan** [comment]
good!

**Pull request merged**
