### PR TITLE
feat : Markdown Link Check Action

### LINKED ISSUE #9721: docs: broken links in Apache APISIX dashboard document
### Current State

**Description of the current state/issue**:
There are many broken links on multiple pages. I can give an example of these. I think tests should be improved to prevent similar issues.
**Link to the page**:
An example situation can be seen in the third step in the link below.
https://apisix.apache.org/docs/dashboard/FAQ/#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

No. Please assign another contributor

### PR DESCRIPTION
**Pull request by utkar-sh-ukla**
Fixes: [#9721](https://github.com/apache/apisix/issues/9721)

I've found an issue with the current approach to finding broken links, as many of the reported broken links are encountering CORS-related errors, not being truly broken. However, we can get accurate results by using the provided [Markdown Link Check](https://github.com/marketplace/actions/markdown-link-check).

Changes:
I have added the action to run `markdown-link-check` in the `link-check` workflow.

Current Issue: 
image

These are not broken links

Fixed Issue:
image

All the links in the file are verified to be correct. 

Additionally, I have addressed the issue where the current approach was mistakenly identifying localhost links as broken links. To fix this, I included a [configuration file](https://github.com/apache/apisix-website/blob/4b80a8486fbcd0df6513f445c68c2244d2e28a76/.github/mlc_config.json) to ignore those specific links during the checking process. Now, the link checker should function more accurately and not flag localhost links as broken.
image

### CODE REVIEW

**Comment by utkar-sh-ukla** [comment]
> https://github.com/apache/apisix-website/pull/1652#issuecomment-1648838898

Hello @SkyeYoung, the Linkinator action was not functioning correctly, so I replaced it with the Markdown link checker action, which is working well. I included the `markdown-link-check` in the "link-check" workflow instead of the deploy workflow. You can find the results of the link checker action at the following link:

https://github.com/apache/apisix-website/actions/runs/5833269753/job/15828457984
See `Run link check` job log

**Comment by LiteSun** [comment]
Please fix ci when you have time.

**Comment by utkar-sh-ukla** [comment]
@LiteSun **CI** fixed.

**Comment by SkyeYoung** [comment]
@bzp2010 Is this ok? 🤔

**Review by SkyeYoung — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
