### PR TITLE
Add new post about webhook and event-driven

### PR DESCRIPTION
**Pull request by Boburmirzo**
Fixes: #[Add issue number here]

Changes:

Developed a new blog post about Event-Driven APIs with Webhook and API Gateway

Screenshots of the change:

The draft version can be found on Dev.to

https://dev.to/bobur/event-driven-apis-with-webhook-and-api-gateway-2l50-temp-slug-6092280?preview=66461d4c1b009601ee05b50dd4e4a51ca63173e6d3c284931c8b39426f92bda427cb7bbca2ab9ad1c96e6b2f5818e44c48aaffbddaac54d26c24c392

### CODE REVIEW

**Comment by Boburmirzo** [comment]
@SylviaBABY, @SkyeYoung @hf400159, @nfrankel @navendu-pottekkat  and @juzhiyuan 

Could you help me to review this?

Thanks!

**Comment by pottekkat** [comment]
Deploy preview of the post: https://deploy-preview-1396--apache-apisix.netlify.app/blog/2022/11/07/webhook-api-gateway-event-driven-apis/

**Review by SylviaBABY — APPROVED** [review]

**Comment by Boburmirzo** [comment]
> Deploy preview of the post: https://deploy-preview-1396--apache-apisix.netlify.app/blog/2022/11/07/webhook-api-gateway-event-driven-apis/

Thanks!

**Review by juzhiyuan — APPROVED** [review]

**Comment by nfrankel** [comment]
I didn't get a chance to review 😅

**Comment by Boburmirzo** [comment]
> I didn't get a chance to review 😅

@nfrankel Ah, I guess it got merged automatically after two approvals:)

Nachalnik, Feel free to leave your comments and I can create another PR and make these changes properly.

**Comment by nfrankel** [comment]
That's fine, I'm not a control freak

**Pull request merged**
