### PR TITLE
feat: add Zh Blogs

### LINKED ISSUE #623: About the i18n of blogs
**Actual Behaviour**

Currently, our blogs are mixed in English and Chinese. All blogs are displayed whether in English or Chinese. This often brings confusion and inconvenience to users of different languages.

**Expected Behaviour**

When the current environment is in English, only English blogs are displayed, and in the Chinese environment, only Chinese blogs are displayed.

After analysis, we can use the [`draft`](https://docusaurus.io/zh-CN/docs/api/plugins/@docusaurus/plugin-content-blog#markdown-frontmatter) property of the markdown file to solve, It means that the current document is still in draft and will not be displayed in the blog.

So because we default to the English environment, add the `draft` property to all Chinese blogs in the `website/blog` directory.

After that, copy all the blog files to the `website/i18n/zh/docusaurus-plugin-content-blog` directory, and then add the `draft` property to all English blogs.

**Note**: draft will still be displayed in development mode, but after build, it works ~

What do you think？

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Fixes: #623

Changes:

made changes  for #470  according to https://www.docusaurus.cn/docs/api/plugins/@docusaurus/plugin-content-blog#i18n

Please review when you are available @juzhiyuan @liuxiran  @bzp2010 @Baoyuantop

### CODE REVIEW

**Comment by Baoyuantop** [comment]
Does it seem that no matter if I change Chinese or English, the blog is always displayed in English？

**Comment by KishaniKandasamy** [comment]
> Does it seem that no matter if I change Chinese or English, the blog is always displayed in English？

Yes. just rechecked this https://www.docusaurus.cn/docs/api/plugins/@docusaurus/plugin-content-blog#i18n .
Please let me know if there is any change to be done.

**Comment by Baoyuantop** [comment]
In #623, the Expected Behaviour is: 
When the current environment is in English, only English blogs are displayed, and in the Chinese environment, only Chinese blogs are displayed.

**Comment by KishaniKandasamy** [comment]
> In #623, the Expected Behaviour is:
> When the current environment is in English, only English blogs are displayed, and in the Chinese environment, only Chinese blogs are displayed.

yes For this behavior I followed this guide https://www.docusaurus.cn/docs/api/plugins/@docusaurus/plugin-content-blog#i18n & will look into that

**Comment by KishaniKandasamy** [comment]
> Does it seem that no matter if I change Chinese or English, the blog is always displayed in English？

Yes ;(
Screenshot 2021-09-25 170633

**Comment by Baoyuantop** [comment]
cc @guoqqqi

**Comment by Baoyuantop** [comment]
Hi @KishaniKandasamy, In general, there are a few things that need to be changed:

1. All blog content should both exist in the `blog` and `i18n/zh/docusaurus-plugin-content-blog` directories.

2. Because the website is in English by default, the blogs in the `blog` directory should all be in English, but we have not yet completed the overall translation, so the Chinese blogs in this directory need to be marked as `draft`, refer to: https://docusaurus.io/zh-CN/docs/api/plugins/@docusaurus/plugin-content-blog#markdown-frontmatter

3. Similarly, the blogs in the `i18n/zh/docusaurus-plugin-content-blog` directory should all be in Chinese, so we need to mark all the English blogs in this directory as `draft`.

We need to complete the translation of the blog marked as `draft` in the future, and then cancel the draft mark.

What do you think?

**Comment by KishaniKandasamy** [comment]
> Hi @KishaniKandasamy, In general, there are a few things that need to be changed:
> 
> 1. All blog content should both exist in the `blog` and `i18n/zh/docusaurus-plugin-content-blog` directories.
> 2. Because the website is in English by default, the blogs in the `blog` directory should all be in English, but we have not yet completed the overall translation, so the Chinese blogs in this directory need to be marked as `draft`, refer to: https://docusaurus.io/zh-CN/docs/api/plugins/@docusaurus/plugin-content-blog#markdown-frontmatter
> 3. Similarly, the blogs in the `i18n/zh/docusaurus-plugin-content-blog` directory should all be in Chinese, so we need to mark all the English blogs in this directory as `draft`.
> 
> We need to complete the translation of the blog marked as `draft` in the future, and then cancel the draft mark.
> 
> What do you think?

I got it @Baoyuantop .Many thanks for this clarification! I'm gonna make this changes :)

**Comment by KishaniKandasamy** [comment]
Hi @Baoyuantop , I have submitted another [PR ](https://github.com/apache/apisix-website/pull/634)for this task.

**Comment by yzeng25** [comment]
Hi @KishaniKandasamy @Baoyuantop , are you guys still working on this PR and https://github.com/apache/apisix-website/pull/550? Or maybe you can close it since it is done in https://github.com/apache/apisix-website/pull/634. Thanks!

**Comment by KishaniKandasamy** [comment]
> Hi @KishaniKandasamy @Baoyuantop , are you guys still working on this PR and #550? Or maybe you can close it since it is done in #634. Thanks!

Hi @Baoyuantop We can close it :)

**Comment by juzhiyuan** [comment]
Hi @KishaniKandasamy, thanks for your continuous contrition! I have translated all necessary blogs in #681 #682 #679 #678 from Chinese to English, so I will close this PR and #550 :)

**Pull request closed without merging**
