### PR TITLE
fix: optimize and remove useless things

### PR DESCRIPTION
**Pull request by SkyeYoung**
Fixes: #[Add issue number here]

Changes:

Screenshots of the change:

### CODE REVIEW

**Review by bzp2010 — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by 1502shivam-singh** [comment]
@SkyeYoung, could you rework/reset, the hero section animation to previous version, because the current one, animation wise, has terribly off spacing and timing.
Also, reset the the graphic in hero/top most section on mobile phones (tbh, there is minimal or almost no performance gain from this change)
Rest I am fine with 👍. Would appreciate you tag me here in case making changes like these.

cc @juzhiyuan @bzp2010 , if you agree with these suggestions, please revert this.

**Comment by SkyeYoung** [comment]
@1502shivam-singh I'm working on that. The reason for this is that the original animation would have to show a lot of blanks on the first load due to the loading speed of GSAP in poor network conditions. So I'm using CSS animations to mimic the original animations (the text part) as much as possible, but I don't have enough time to tweak it enough.
The mobile part is also being tweaked.

**Comment by 1502shivam-singh** [comment]
Oh, okay. Nice initiative from your side. I would have really assisted you on this if I didn't have other work priorities (sad).
Even so, maybe this will help you. Use the below mentioned code to understand the easing curve type, durations and gaps (stagger) between intermediate animation.


```
    const tl = gsap.timeline({
      defaults: {
        ease: 'Expo.easeInOut',
      },
    });

    tl.fromTo([titleRef.current, subtitleRef.current, ctaRef.current], {
      opacity: 0,
      y: 10,
    }, {
      opacity: 1,
      y: 0,
      stagger: 0.3,
    });
```

Then, edit this animation that you have defined -

```
.hide-title,
.hide-subtitle,
.hide-ctas {
  opacity: 0;
@keyframes fade-in-up {
  from {
    opacity: 0;
    transform: translate3d(0, 50%, 0);
  }

  to {
    opacity: 1;
    transform: translate3d(0, 0, 0);
  }
}

.hero-title,
.hero-subtitle,
.hero-ctas {
  animation-name: fade-in-up;
  animation-fill-mode: both;
  animation-delay: 0s;
  animation-duration: 1s;
}

.
.
.
```

**Comment by SkyeYoung** [comment]
@1502shivam-singh Thank you! I will start working on this as soon as possible!

**Pull request merged**
