### PR TITLE
docs: update images in tencent cloud blog

### PR DESCRIPTION
**Pull request by yzeng25**
Changes:

Update images in this blog.

Screenshots of the change (Updated)

### CODE REVIEW

**Comment by yzeng25** [comment]
Preview: https://deploy-preview-952--apache-apisix.netlify.app/blog/2021/09/16/tencent-cloud
Actual: https://apisix.apache.org/blog/2021/09/16/tencent-cloud

**Review by SylviaBABY — DISMISSED** [review]

**Comment by moonming** [comment]
Can you change the font in iamges? can not see clearly

**Comment by yzeng25** [comment]
> Can you change the font in iamges? can not see clearly


Is this font ok? If it is ok, I can change them.

**Comment by moonming** [comment]
LGTM

Thanks,
Ming Wen
Twitter: _WenMing


yilinzeng ***@***.***> 于2022年3月9日周三 17:47写道：

**Review by SylviaBABY — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
