### PR TITLE
docs: Updated Blog Contributing Guide page

### LINKED ISSUE #879: Improving the Blog Contributing Guide page
**Actual Behaviour**

While going through the Blog Contributing Guide page, I found various typos and grammatical errors that need to be addressed and fixed.

**Expected Behaviour**

 Fix the issues on the Blog Contributing Guide page. Record similar issues, if they exist, on any other page.

**Steps to reproduce it**

The section of the website under consideration can be accessed using the following link.
https://apisix.apache.org/docs/general/blog

**Screenshots of the issue**

image

**Would you like to work on the issue?**

 Yes, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by BeeBombshell**
Fixes: #879 

Changes:

Fixed typos and grammatical errors on the Blog Contributing Guide page

Screenshots of the change:

image

### CODE REVIEW

**Comment by BeeBombshell** [comment]
@juzhiyuan @shuaijinchao kindly review the PR... 😊

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Review by shuaijinchao — APPROVED** [review]
LGTM

**Review by Baoyuantop — APPROVED** [review]

**Review by yzeng25 — APPROVED** [review]

**Comment by yzeng25** [comment]
@BeeBombshell good job! Glad to see this PR :)

**Pull request merged**
