### PR TITLE
chore: support dark mode and switch

### PR DESCRIPTION
**Pull request by Yiyiyimu**
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>

Screenshots of the change:

image

### CODE REVIEW

**Comment by Yiyiyimu** [comment]
An awkward thing is when text is not in black (for example some dark grey), dark mode seems could not get its opponent color...

image

One possible solution to deal with this situation is like the tagline of https://docusaurus.io/, to make it stale and not get affected by the dark mode.

**Light mode**
image

**Dark mode**
image

I tried to find the method to make it stale but failed 😿 crying again for not familiar with frontend

**Comment by jbampton** [comment]
I think for sure it's like JS/CSS/HTML but I suck at front end too.  
You may have seen some of my sites it's all weird purple disco.
But for sure dark mode is important so we need this

**Review by juzhiyuan — APPROVED** [review]
Though it's wired due to some color issues, we still need this.

**Review by tokers — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
> Though it's wired due to some color issues, we still need this.

I'll create a new issue for this

**Pull request merged**
