### PR TITLE
feat: Add the DockerHub links on Downloads page

### LINKED ISSUE #767: Add the DockerHub links on Downloads page
**Actual Behaviour**

We have a download page here[1], it supports the latest version of source codes, we could provide more ways to download package 😄

[1] https://apisix.apache.org/downloads

**Solution**

We support RPM/Docker/Helm ways to get package, we could generate or add their links on the download page.

### PR DESCRIPTION
**Pull request by oil-oil**
Fixes: #767 

Changes:

Add the DockerHub links on Downloads page.

Screenshots of the change:

image

### CODE REVIEW

**Review by juzhiyuan — DISMISSED** [review]
LGTM

**Review by 1502shivam-singh — DISMISSED** [review]
LGTM, please resolve the conflicts though

**Comment by oil-oil** [comment]
> LGTM, please resolve the conflicts though

OK.

**Review by Baoyuantop — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by oil-oil** [comment]
@juzhiyuan Can you help me re-execute the CI, I can pass the test in the development environment.

**Comment by oil-oil** [comment]
@yzeng25 Can you help me re-execute the CI, I can pass the test in the development environment.

**Comment by yzeng25** [comment]
> @yzeng25 Can you help me re-execute the CI, I can pass the test in the development environment.

ok, it is up and re-running now.

**Review by yzeng25 — APPROVED** [review]

**Pull request merged**
