### PR TITLE
blog: data mask plugin

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: Navendu Pottekkat <navendu@apache.org>

New blog post titled "Creating a Custom Data Mask Plugin."

### CODE REVIEW

**Comment by pottekkat** [comment]
The other lint errors are from a different file.

**Comment by yzeng25** [comment]
> The other lint errors are from a different file.

I created a pr to fix those lint errors, see https://github.com/apache/apisix-website/pull/1639.

**Comment by pottekkat** [comment]
@yzeng25 Thank you. I will rebase this PR after we merge your PR.

**Comment by yzeng25** [comment]
Ready for rebase as #1639 is merged @navendu-pottekkat .

**Comment by pottekkat** [comment]
@yzeng25 Done. Thanks.

**Review by juzhiyuan — APPROVED** [review]

**Review by yzeng25 — APPROVED** [review]

**Pull request merged**
