### PR TITLE
feat: added company who uses Apache APISIX logo

### PR DESCRIPTION
**Pull request by Serendipity96**
Changes:

feat: added company who uses Apache APISIX logo, these company are from Apache APISIX 2nd anniversary gift collection questionnaire.

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
I'll fix those icon for appearance in both light and dark mode

**Comment by Yiyiyimu** [comment]
Besides add an alpha channel to all icons, also did the following things

1. Remove [`zhi20`](http://www.zhi20.com/) due to [suspected pyramid scheme](https://www.163.com/dy/article/G6JJGB4G0534JSFW.html)
2. Remove [`zihaowangluo`](http://sms.gs/) since it's an outsourcing company
3. Change icon and website from `manbang` to its actual app `yunmanman`, since I think we tend to use app but not the company to present our users
4. Remove [`magichill`](https://web.archive.org/web/2020*/http://www.magichill.cn/) since its website has already shut down and I guess the same with the company
5. Change `topsec` from https://www.topsectechnology.com/Home.html to https://www.topsec.com.cn/, since the latter one seems to have a larger chance to use APISIX. Correct me if I'm wrong @Serendipity96 

cc @juzhiyuan

**Review by juzhiyuan — APPROVED** [review]
LGTM!!

**Review by LiteSun — APPROVED** [review]
LGTM

**Pull request merged**
