### PR TITLE
Change publish branch for GitHub Action

### LINKED ISSUE #215: Fix wrong GitHub Action
We need to fix the GitHub Action so it could push bundled files to `asf-site` branch instead of `gh-pages`.

related issue https://github.com/apache/incubator-apisix-dashboard/issues/213

### PR DESCRIPTION
**Pull request by yujqiao**
Fix https://github.com/apache/incubator-apisix-dashboard/issues/215

### CODE REVIEW

**Comment by yujqiao** [comment]
@juzhiyuan Kindly review

**Comment by juzhiyuan** [comment]
Thanks!

**Comment by juzhiyuan** [comment]
Hi @Rapiz1 , not sure what happened... but after deployment, the commit removes most of the contents ...

https://github.com/apache/incubator-apisix-website/commit/bd6283d6b0864d25b7b172155534419e2d27ae24

**Comment by juzhiyuan** [comment]
image

This my Hugo version..

**Comment by yujqiao** [comment]
On my machine, `hugo` produces the same output as GitHub Action. It may be related to the version. I will look into it.

**Comment by juzhiyuan** [comment]
@Rapiz1  It looks better! but still has someting wrong 🤔

[This page](https://apisix.apache.org/team/) lost its styles, because of this commit.

https://github.com/apache/incubator-apisix-website/commit/6722e83f5edb390e6169c08d78d57fb0c9696753

**Comment by juzhiyuan** [comment]
And this one https://apisix.apache.org/downloads/

**Comment by juzhiyuan** [comment]
Just created a PR here https://github.com/apache/incubator-apisix-dashboard/issues/216

**Pull request merged**
