### PR TITLE
chore: Adjusting the page layout 

### PR DESCRIPTION
**Pull request by juxianzheng**
Fixes: Now look at the layout is too small, need to be optimized, adjust the page layout, I made a few changes in the layout of.
1, the entire layout of the padding left and right to increase the width
2, all the pictures are enlarged to twice the previous
 #1027
Changes:

https://apisix.apache.org/zh/showcase/

Screenshots of the change:

image

### CODE REVIEW

**Comment by SkyeYoung** [comment]
Hi, I asked some questions in https://github.com/apache/apisix-website/issues/1027#issuecomment-1098643265.

I think we can answer the questions before starting the review.

**Comment by juxianzheng** [comment]
@guoqqqi  @baoyuantop
 I'm done with you all to see what you have to say

**Comment by SkyeYoung** [comment]
@juxianzheng Any update here?

**Comment by guoqqqi** [comment]
will be updated on another PR

**Pull request closed without merging**
