### PR TITLE
fix: abnormal display of dividing line in blog

### LINKED ISSUE #555: Bug: extra '|' shown in the blog list
**Actual Behaviour**

image

image

There is an extra '|' shown in the blog list

we should remove it.

### PR DESCRIPTION
**Pull request by Baoyuantop**
Fixes: #555 

Changes:

On the blog page, when the author or tags is null, cancel display `|`.

Screenshots of the change:

image

image

### CODE REVIEW

**Comment by liuxiran** [comment]
Hi @Baoyuantop , how about cancel the margin when the info shown at the first please?

image

**Comment by Baoyuantop** [comment]
> Hi @Baoyuantop , how about cancel the margin when the info shown at the first please?
> 
> image

Yes, I will adjust

**Comment by Baoyuantop** [comment]
cc @liuxiran

**Review by liuxiran — APPROVED** [review]
LGTM

**Comment by liuxiran** [comment]
also cc @1502shivam-singh @KishaniKandasamy @iamayushdas @bzp2010 to have a look, thanks

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
