### PR TITLE
chore: added uniform id's for documentations

### LINKED ISSUE #363: implementing uniform doc page `id` for all documentation
**Actual Behaviour**

The page id is not uniform for any of the documentations present in website

**Expected Behaviour**

There should be a uniformity in id for all docs of our sub projects.

1. you can see here in screenshots that id is random for every page
2. having uniform id's are very useful for developers to play with the DOM and implementing new features

**Screenshots of the issue**

Screenshot from 2021-06-11 12-27-12
Screenshot from 2021-06-11 12-26-29

**Proposed solution**
Making uniform subheadings to every documentation.

**Would you like to work on the issue?**

Yes i would like to work on it

@juzhiyuan @Yiyiyimu please share your opinion

### PR DESCRIPTION
**Pull request by iamayushdas**
Fixes: #363 

Changes:

1. added uniform id's
2. fixed the navigation path name for java-runner

### CODE REVIEW

**Comment by iamayushdas** [comment]
cc @juzhiyuan @Yiyiyimu

**Review by juzhiyuan — DISMISSED** [review]

**Comment by juzhiyuan** [comment]
@iamayushdas Hi, would you mind pasting the Docusarus's feature page? so we could know which feature it provides :)

**Comment by iamayushdas** [comment]
> @iamayushdas Hi, would you mind pasting the Docusarus's feature page? so we could know which feature it provides :)


image

v2.0.0beta - https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.1

**Comment by iamayushdas** [comment]
This is the way of adding id's to the page for executing DOM manipulations and other things more clearly, its not a whole feature, its just a part of other doc based features. hope you understood what I mean, @juzhiyuan

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
yes, more clearer.

**Review by Yiyiyimu — APPROVED** [review]

**Comment by iamayushdas** [comment]
this shouldn't be merge right now, this feat  is in a discussion period right now, should I revert the PR? @juzhiyuan @Yiyiyimu

**Comment by juzhiyuan** [comment]
Yes, and you should mark this PR as Draft :) Please revert it and draft your other PRs before we have agreement.

**Comment by iamayushdas** [comment]
> Yes, and you should mark this PR as Draft :) Please revert it and draft your other PRs before we have agreement.

okay doing it

**Pull request merged**
