### PR TITLE
 add observability CN blog

### PR DESCRIPTION
**Pull request by yzeng25**
Changes:
add observability blog in Chinese by Wei Jin

### CODE REVIEW

**Comment by Yangxiamao** [comment]
This pr done the same work as the previous one.
https://github.com/apache/apisix-website/pull/528

**Comment by Yangxiamao** [comment]
This pr done the same thing as https://github.com/apache/apisix-website/pull/528.

**Comment by yzeng25** [comment]
> This pr done the same work as the previous one.
> #528

OK.

**Comment by yzeng25** [comment]
Changes made in this pr and https://github.com/apache/apisix-website/pull/528 are almost the same, close this one  and keep https://github.com/apache/apisix-website/pull/528 to reduce confusions.

**Pull request closed without merging**
