### PR TITLE
feat: versioning Chinese docs

### LINKED ISSUE #354: bug: Official website Chinese doc showing English
All of them, e.g. https://apisix.apache.org/zh/docs/apisix/getting-started/

### PR DESCRIPTION
**Pull request by qier222**
Fixes: #[Add issue number here]

Changes:

Screenshots of the change:

### CODE REVIEW

**Comment by qier222** [comment]
Preview: https://60b07a3cbb59fb5d1bcfd1ee--apisix.netlify.app/

**Review by juzhiyuan — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
It seems `sync-doc` in `check broken links` failed

**Comment by juzhiyuan** [comment]
cc @qier222

**Comment by juzhiyuan** [comment]
@Yiyiyimu Hi, this issue is fixed :)

**Review by iamayushdas — APPROVED** [review]

**Review by Yiyiyimu — APPROVED** [review]

**Pull request merged**
