### PR TITLE
docs: Updated Contributor Guide page and Committer Guide page

### PR DESCRIPTION
**Pull request by BhavyaT-135**
As discussed in #879, 
> Hi @juzhiyuan, @shuaijinchao, @BeeBombshell I found similar issues on the Contributor Guide page as well. I would like to work on that and fix the documentation. Should I file a new issue or submit a PR in this issue itself?

Changes:

Fixed typos and grammatical errors on the Contributing Guide page and the Committer Guide page.

Screenshots of the change:

image

### CODE REVIEW

**Comment by BhavyaT-135** [comment]
Hi @juzhiyuan, @yzeng25 could you please take a look at the PR... :)

**Comment by yzeng25** [comment]
> Hi @juzhiyuan, @yzeng25 could you please take a look at the PR... :)

Nice. I'

> Hi @juzhiyuan, @yzeng25 could you please take a look at the PR... :)

Nice, I will approve to get the rest of workflows running.

**Comment by yzeng25** [comment]
> Hi @juzhiyuan, @yzeng25 could you please take a look at the PR... :)

Nice, I will approve to get the rest of workflows running.

**Review by yzeng25 — APPROVED** [review]

**Review by shuaijinchao — APPROVED** [review]
LGTM, great

**Comment by lijing-21** [comment]
Hi @BhavyaT-135  , thank you for your contribution!

Here is the Contributor T-shirt form[1], if you're interested, kindly take a look :)

[1] https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#contributor-t-shirt

**Pull request merged**
