### PR TITLE
docs: update featured article list

### PR DESCRIPTION
**Pull request by guitu168**
Fixes: #[Add issue number here]

Changes:

Screenshots of the change:

### CODE REVIEW

**Review by SylviaBABY — DISMISSED** [review]

**Review by SylviaBABY — DISMISSED** [review]

**Comment by yzeng25** [comment]
Did you all check the preview environment? This does not look right. @hf400159 @SylviaBABY 

image

**Comment by yzeng25** [comment]
With this modification, both [blog](https://deploy-preview-1301--apache-apisix.netlify.app/blog/) and [Case Studies (which is also a part of blog)](https://deploy-preview-1301--apache-apisix.netlify.app/blog/tags/case-studies/) in en-us and zh-cn failed.

I'd suggest solving these failures before merging, otherwise this could be a huge problem. You can seek help from others in the community as well.

**Review by yzeng25 — DISMISSED** [review]
You need to solve 404s in blog and case study first.

1. https://deploy-preview-1301--apache-apisix.netlify.app/blog/
2. https://deploy-preview-1301--apache-apisix.netlify.app/blog/tags/case-studies/
3. https://deploy-preview-1301--apache-apisix.netlify.app/zh/blog
4. https://deploy-preview-1301--apache-apisix.netlify.app/zh/blog/tags/case-studies/

**Comment by guitu168** [comment]
Hi, I found this problem yesterday; I will fix it today. @yzeng25

**Review by SylviaBABY — DISMISSED** [review]

**Review by SylviaBABY — APPROVED** [review]
LGTM, all preview links back to normal

**Review by SkyeYoung — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Hi @yzeng25, sorry to dismiss your Request Change, this PR has fixed that issue.

**Comment by yzeng25** [comment]
> Hi @yzeng25, sorry to dismiss your Request Change, this PR has fixed that issue.

Yeah no problem.

**Pull request merged**
