### PR TITLE
fix: removed duplicated `ip-restriction` plugin

### PR DESCRIPTION
**Pull request by kayx23**
Currently there are two: 
dup

### CODE REVIEW

**Comment by kayx23** [comment]
@guoqqqi

**Review by guoqqqi — APPROVED** [review]

**Comment by kayx23** [comment]
@juzhiyuan : )

**Comment by kayx23** [comment]
@juzhiyuan

**Comment by kayx23** [comment]
Hi just a friendly reminder for reviewers. Small change.

**Review by yzeng25 — APPROVED** [review]

**Pull request merged**
