### PR TITLE
feat: Add a bundle of Good first issues links to Homepage

### LINKED ISSUE #178: Add a bundle of Good first issues links to Homepage
Add a bundle of Good first issues Section to the Homepage.

[1] https://github.com/apache/apisix#community

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Fixes: #178

Changes:

update homepage

Screenshots of the change:

Screenshot (64)

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi, I'm not sure if we need those 3 buttons 😂 need @qier222 @1502shivam-singh 's confirm

**Comment by KishaniKandasamy** [comment]
> Hi, I'm not sure if we need those 3 buttons 😂 need @qier222 @1502shivam-singh 's confirm

**Comment by 1502shivam-singh** [comment]
I too feel the same, no need for 3 buttons. A "View on GitHub" is in most cases enough, we have a **contribution guidelines** section to handle too. So, making a "View on Github" as primary and "See guidelines" button as secondary would do. 
**We can try hyperlinks too** if buttons seem an overkill. 
If you are going to use buttons, check that first the primary one comes, then the secondary.

**Comment by 1502shivam-singh** [comment]
> > Hi, I'm not sure if we need those 3 buttons 😂 need @qier222 @1502shivam-singh 's confirm
> 
> 

The key is the presentation, check that you have used buttons, while there they have used hyperlinks.
Buttons seem an overkill and almost intrusive for this cause. More of a problem with UI choice, might try some different UI pattern to make it look good while still using buttons instead of a simple center aligned section.
Three buttons also lead to UX problems, like too many choices, overwhelming for users (Depends on visual arrangment). While hyperlinks don't as they are smaller in size and lesser overwhelming than buttons.

**Comment by KishaniKandasamy** [comment]
> > > Hi, I'm not sure if we need those 3 buttons 😂 need @qier222 @1502shivam-singh 's confirm
> > 
> > 
> > 
> 
> The key is the presentation, check that you have used buttons, while there they have used hyperlinks.
> Buttons seem an overkill and almost intrusive for this cause. More of a problem with UI choice, might try some different UI pattern to make it look good while still using buttons instead of a simple center aligned section.
> Three buttons also lead to UX problems, like too many choices, overwhelming for users (Depends on visual arrangment). While hyperlinks don't as they are smaller in size and lesser overwhelming than buttons.

Okay Thanks for the feedback

**Pull request closed without merging**
