### PR TITLE
feat: added java plugin runner download block

### LINKED ISSUE #406: feature: update download page to add apisix-java-plugin-runner
**Actual Behaviour**

 

**Expected Behaviour**

The download page shows the download information of apisix-java-plugin-runner.
 

**Steps to reproduce it**

 

**Screenshots of the issue**

 

**Would you like to work on the issue?**

### PR DESCRIPTION
**Pull request by iamayushdas**
Fixes: #406 

Changes:

added download card for apish java plugin runner

Screenshots of the change:

image

### CODE REVIEW

**Comment by iamayushdas** [comment]
cc @juzhiyuan @Yiyiyimu @guoqqqi

**Comment by iamayushdas** [comment]
unexpected ci error @juzhiyuan

**Comment by juzhiyuan** [comment]
image
🤔

**Comment by juzhiyuan** [comment]
see 770, CI runs `git checkout -f WRONG_BRANCH`

**Comment by iamayushdas** [comment]
> see 770, CI runs `git checkout -f WRONG_BRANCH`

but I haven't changed that code, I guess some breaking changes have been merged to apisix dashboard @juzhiyuan

**Comment by iamayushdas** [comment]
@LiteSun can you have a peek on this

**Comment by juzhiyuan** [comment]
What will happen when you run `sync-docs.js` on your local machine?

**Comment by iamayushdas** [comment]
image

I even have tried by cloning new fresh repo
@juzhiyuan

**Comment by juzhiyuan** [comment]
image

Need to take a look at what's this `[object Object]` is 🤣

**Comment by iamayushdas** [comment]
> image
> 
> Need to take a look at what's this `[object Object]` is 🤣

okay have a look please

**Comment by juzhiyuan** [comment]
@iamayushdas look which one?

**Comment by iamayushdas** [comment]
> @iamayushdas look which one?

This error,

**Comment by juzhiyuan** [comment]
I still couldn't see what's the content of that `[object Object]`, please print it. You may need `JSON.stringify` to handle it.

**Comment by iamayushdas** [comment]
cc @juzhiyuan image

**Comment by Yiyiyimu** [comment]
Hi @iamayushdas Do you know how are we building multi-version docs for now? I created an extra branch in apisix-docker repo but it seems we should not build on all branches but the selected ones

**Comment by iamayushdas** [comment]
I got you @Yiyiyimu  Ohhhhh! Thats where the problem arises, but we are just using main/master branches, let me reconfirm with @juzhiyuan

**Comment by juzhiyuan** [comment]
Just fixed this issue here https://github.com/apache/apisix-website/pull/412/files#diff-2c12df13ad0ff398ec46834d8336f3d6e5089a89a1d2b7c39f5f209abcec0217R163

And yes, we only build branches like `release/xxx`, because @Yiyiyimu's branch in apisix-docker contains `release` keyword, then this build failed. I just updated it to `release/`.

**Comment by juzhiyuan** [comment]
After #412 gets merged, please sync codes from the master branch.

**Comment by iamayushdas** [comment]
> Just fixed this issue here https://github.com/apache/apisix-website/pull/412/files#diff-2c12df13ad0ff398ec46834d8336f3d6e5089a89a1d2b7c39f5f209abcec0217R163
> 
> 
> 
> And yes, we only build branches like `release/xxx`, because @Yiyiyimu's branch in apisix-docker contains `release` keyword, then this build failed. I just updated it to `release/`.

Nice, thankyou

**Comment by juzhiyuan** [comment]
@iamayushdas You need more patience and focus on why this error occurred, just go through the codes and think why.

**Comment by iamayushdas** [comment]
> @iamayushdas You need more patience and focus on why this error occurred, just go through the codes and think why.

I acknowledge this, thanks

**Comment by juzhiyuan** [comment]
just merged, please sync master branch.

**Review by juzhiyuan — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Pull request merged**
