### PR TITLE
feat: add vercel preview

### PR DESCRIPTION
**Pull request by bzp2010**
Changes:

Add PR preview to the repo. Powered by Vercel.

Screenshots of the change:

image

At same time, you can see the GitHub Workflow running example [**link here**](https://github.com/bzp2010/apisix-website/tree/feat-vercel-preview)

### CODE REVIEW

**Comment by bzp2010** [comment]
About this plan:
The website content is built by GitHub workflow, compressed into `tar.gz` volume files, and then uploaded to Vercel for decompression and deployment.

About Vercel:
Currently, it provides
- 45 minutes of compile time for each project‘s each CI
- 5000 API requests per day

it limitations (Hobby)
image


> Because our project has too many files after compilation and cannot be uploaded to Vercel one by one, I solve this problem by compressing, uploading and decompressing. 


At the same time, we need to contact infra of ASF to add `Environment Secret` to our repo and obtain a GitHub token to automatically publish PR comment for preview URL.

**Comment by bzp2010** [comment]
Hi, @liuxiran. Please hava a look. XD

**Comment by juzhiyuan** [comment]
> At the same time, we need to contact infra of ASF to add Environment Secret to our repo and obtain a GitHub token to automatically publish PR comment for preview URL.

@bzp2010 Hi, may I know if this gets done?

**Comment by bzp2010** [comment]
@juzhiyuan, This PR is currently waiting for infra to add secret environment variables.
 
[Infra Ticket](https://issues.apache.org/jira/browse/INFRA-22337)

**Review by liuxiran — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
