### PR TITLE
docs: update contents for SEO

### PR DESCRIPTION
**Pull request by yzeng25**
Changes:

- Rename files in a more semantic way
- Add Apache APISIX intro to articles

### CODE REVIEW

**Review by SylviaBABY — APPROVED** [review]

**Review by guitu168 — COMMENTED** [review]
Do we need to update keywords?

**Comment by yzeng25** [comment]
> Do we need to update keywords?

Nope, they should be fine.

**Review by moonming — CHANGES_REQUESTED** [review]
1. please add `API Gateway` in URI.
2. add `API gateway` in keywords.

**Review by moonming — CHANGES_REQUESTED** [review]
There are still many articles that have not been updated

**Pull request closed without merging**
