### PR TITLE
docs: fixed kubernetes service api broken link

### LINKED ISSUE #326: docs: many broken links our residing in website
**Actual Behaviour**

Many of the links are broken

**Expected Behaviour**

All the links should be working fine

**Steps to reproduce it**

Check ingress and helm pages

**Screenshots of the issue**

 
Screenshot from 2021-04-30 22-22-14
Screenshot from 2021-04-30 22-24-18

**Would you like to work on the issue?**

yes i would like to work on this issue

### PR DESCRIPTION
**Pull request by xdshivani**
Fixes: #326 

Changes:
fixed kubernetes service api broken link

Thankyou @iamayushdas for making me understand architecture of apisix-website. 
Here is my first PR 
Have a look to this

### CODE REVIEW

**Review by iamayushdas — APPROVED** [review]
LGTM.

@tokers @Yiyiyimu have a review to this

**Review by juzhiyuan — APPROVED** [review]
Just to make sure, do we have other URLs using `https://kubernetes-sigs.github.io/service-apis/`?

**Review by Yiyiyimu — CHANGES_REQUESTED** [review]
There are quite a lot of broken links found in #326, we'd better fix them all together in this PR

**Comment by xdshivani** [comment]
> There are quite a lot of broken links found in #326, we'd better fix them all together in this PR

I tried to search those links in every repositories, but those links doesn't exist now. @iamayushdas could you check the issue once again.

**Comment by iamayushdas** [comment]
> > There are quite a lot of broken links found in #326, we'd better fix them all together in this PR
> 
> 
> 
> I tried to search those links in every repositories, but those links doesn't exist now. @iamayushdas could you check the issue once again.

Oh yes, zh folder doesn't exist now in docs. You can look for other links, if all links are working fine just ping me here. 
Thank you for contribution

**Comment by Yiyiyimu** [comment]
> I tried to search those links in every repositories, but those links doesn't exist now. @iamayushdas could you check the issue once again.

The reason those links are broken is due to, apisix-ingress-controller does not contain Chinese doc, but on Chinese website, the edit link is pointing to `zh` link. So the logic of multi-language doc edit links need to fix. But we could leave it to another PR.

**Comment by iamayushdas** [comment]
> > I tried to search those links in every repositories, but those links doesn't exist now. @iamayushdas could you check the issue once again.
> 
> The reason those links are broken is due to, apisix-ingress-controller does not contain Chinese doc, but on Chinese website, the edit link is pointing to `zh` link. So the logic of multi-language doc edit links need to fix. But we could leave it to another PR.

yes ofcourse, will look into it in another PR
Thanks for review

**Comment by Yiyiyimu** [comment]
What about other links, like etcd/travelsky/aliyun

**Review by tokers — APPROVED** [review]

**Comment by iamayushdas** [comment]
@xdshivani kindly have a look on other broken links residing there too like etcd/travelsky/aliyun

**Review by KishaniKandasamy — APPROVED** [review]

**Comment by LiteSun** [comment]
ping~

**Comment by Yiyiyimu** [comment]
@LiteSun @xdshivani some other links need to be fixed

**Comment by xdshivani** [comment]
1. I am new to open source and I don't know why I am receiving these errors.
2. I tried to find the broken links in local repo but, could not find it.
3. The only faulty link I got was of kubernetes link and I fixed it in this PR @Yiyiyimu  @iamayushdas

**Comment by iamayushdas** [comment]
@xdshivani 
see here for some reference
sinog2c.com

**Comment by iamayushdas** [comment]
> @xdshivani
> see here for some reference
> sinog2c.com

use this link instead: http://www.sinog2c.com/

**Comment by iamayushdas** [comment]
@xdshivani
see here for some reference
 sinog2c.com

use these links instead: 
http://www.sinog2c.com/
https://www.travelsky.com.cn/
https://partners-intl.aliyun.com/help/doc-detail/142666.htm  for [Log server]
https://partners-intl.aliyun.com/help/doc-detail/25485.htm for [serve list]
https://www.alibabacloud.com/help/doc-detail/182218.htm [access services through SLB]

hope it helps

**Comment by Yiyiyimu** [comment]
The etcd link should be https://github.com/etcd-io/website/blob/main/content/en/docs/next/learning/why.md, but I also failed to locate where is this link. Hi @iamayushdas could you offer some help

**Comment by iamayushdas** [comment]
> The etcd link should be https://github.com/etcd-io/website/blob/main/content/en/docs/next/learning/why.md, but I also failed to locate where is this link. Hi @iamayushdas could you offer some help

It would be a pleasure to help

**Comment by iamayushdas** [comment]
> The etcd link should be https://github.com/etcd-io/website/blob/main/content/en/docs/next/learning/why.md, but I also failed to locate where is this link. Hi @iamayushdas could you offer some help

It is already fixed now, thats why you aren't able to find the link

**Review by Yiyiyimu — APPROVED** [review]

**Pull request merged**
