### PR TITLE
blog: Add Even more Opentelemetry post

### PR DESCRIPTION
**Pull request by nfrankel**
Please don't merge before June 6th

Screenshot 2024-05-29 at 11 56 56

### CODE REVIEW

**Review by shreemaan-abhishek — COMMENTED** [review]
should this blog go to the apisix website? I can barely see anything about APISIX here.

**Comment by nfrankel** [comment]
@shreemaan-abhishek that's the question i asked internally twice and nobody answered 🤬

**Comment by yzeng25** [comment]
> @shreemaan-abhishek that's the question i asked internally twice and nobody answered 🤬

@moonming wdyt

**Review by moonming — APPROVED** [review]
looks good to me

**Review by pottekkat — APPROVED** [review]

**Pull request merged**
