### PR TITLE
fix: added navigation path name for Go Runner

### PR DESCRIPTION
**Pull request by iamayushdas**
Fixes: #[Add issue number here]

Changes:

fixed navigation path name for Go Runner

Screenshots of the change:

Untitled

### CODE REVIEW

**Comment by iamayushdas** [comment]
cc @Yiyiyimu @juzhiyuan

**Review by juzhiyuan — APPROVED** [review]
Should be plugin runner?

**Comment by iamayushdas** [comment]
Yes but the it was already labelled as `Go Runner` so i keep it like that only,
Should i change both?

**Comment by juzhiyuan** [comment]
just wait for other reviewers

**Comment by iamayushdas** [comment]
> just wait for other reviewers

fixed after #405

**Comment by Yiyiyimu** [comment]
@iamayushdas do you mind merge master to see the change in #405

**Comment by iamayushdas** [comment]
@Yiyiyimu have a look

**Review by juzhiyuan — APPROVED** [review]

**Review by Yiyiyimu — APPROVED** [review]

**Pull request merged**
