### PR TITLE
feat: support language detection

### LINKED ISSUE #743: support language detection
**Actual Behaviour**

When users visit apisix.apache.org, our website will serve content in English by default.

**Expected Behaviour**

For users in Chinese, we could provide default Chinese contents for a quick and better involving experiment.

**Solution**

According to https://docusaurus.io/docs/i18n/introduction#i18n-non-goals, Docusaurus will not do language detection, see https://github.com/facebook/docusaurus/issues/5838#issuecomment-955278743 .

Maybe we could use this package? https://www.npmjs.com/package/detect-browser-language

### PR DESCRIPTION
**Pull request by oil-oil**
Fixes: #743

Changes:

Added a method to check the browser language and jump to the Chinese page if the language is Chinese.

Screenshots of the change:

no

### CODE REVIEW

**Comment by bzp2010** [comment]
One problem I found now is that when a user using Chinese needs to view an English document, it will be brought back to Chinese mode again and we need to allow users to manually switch to English documents.

**Comment by oil-oil** [comment]
> One problem I found now is that when a user using Chinese needs to view an English document, it will be brought back to Chinese mode again and we need to allow users to manually switch to English documents.

OK, i'll check it out.

**Comment by oil-oil** [comment]
> One problem I found now is that when a user using Chinese needs to view an English document, it will be brought back to Chinese mode again and we need to allow users to manually switch to English documents.

I thought about it, but there seems to be no good solution to this problem at present. And if the Chinese content is missing in the future, it is not advisable to directly jump to the Chinese page.🧐

**Comment by juzhiyuan** [comment]
> 

Yes, we could have more discussions on the issue before coding 🤗 I will add discuss label to that issue.

**Review by yzeng25 — APPROVED** [review]

**Comment by SkyeYoung** [comment]
This maybe should be closed.

**Comment by juzhiyuan** [comment]
Indeed. We have implemented :)

**Pull request closed without merging**
