### PR TITLE
fix: darkMode enhanced

### LINKED ISSUE #291: bug: dark mode not fully support homepage
An awkward thing is when text is not in black (for example some dark grey), dark mode seems could not get its opponent color...

image

One possible solution to deal with this situation is like the tagline of https://docusaurus.io/, to make it stale and not get affected by the dark mode.

**Light mode**
image

**Dark mode**
image

I tried to find the method to make it stale but failed 😿 crying again for not familiar with frontend

### PR DESCRIPTION
**Pull request by iamayushdas**
Signed-off by: Ayush Das (ayush24das@gmail.com)

Fixes: #291 

Changes:

Dark mode fixed and enhanced

Screenshots of the change:

[Website change 1](https://user-images.githubusercontent.com/40708551/114260533-16968d00-99f3-11eb-9c94-3da6bf478f4f.png)

### CODE REVIEW

**Comment by iamayushdas** [comment]
@juzhiyuan @nic-chen

**Comment by iamayushdas** [comment]
@juzhiyuan @nic-chen have a look

**Comment by juzhiyuan** [comment]
really dark 😂 how about others?

**Comment by iamayushdas** [comment]
> really dark 😂 how about others?

Is this a positive feedback ?

**Comment by Yiyiyimu** [comment]
Post my comments here

> @iamayushdas Nice! For me, I have some other suggestions. Just take it or leave it with your preferences 😁
> 
> 1. It might be a good idea to propose a PR, so we could have a more instinctive view of the actual website rather than screenshots
> 2. For the description part, IMO, we could have a darker background with lighter(whitish) text to be compatible with other parts of the whole website. And still, the background of this part better different from other ones.
> 3. Grayish title is absolutely great, it's the main part of the dark mode. But the problem is it seems too dark right now so the contract between text and background is not clear enough. A example from DuckDuckGo
>    image

**Comment by Yiyiyimu** [comment]
Also it seems you also change some color in the light mode, like the github button, which seems not as good as before.

**Comment by juzhiyuan** [comment]
@iamayushdas no 😂 I mean we need more contributors review.

**Comment by iamayushdas** [comment]
> @iamayushdas no 😂 I mean we need more contributors review.

Oh okay😅

**Comment by iamayushdas** [comment]
> Also it seems you also change some color in the light mode, like the github button, which seems not as good as before.

Let me acquire what you said😊

**Comment by iamayushdas** [comment]
@gxthrj @nic-chen need a review on this!

**Comment by iamayushdas** [comment]
@Yiyiyimu @juzhiyuan @nic-chen @gxthrj 
How is it now?
[Website change 2](https://user-images.githubusercontent.com/40708551/114266705-4b1b4080-9a15-11eb-9f36-3581053eef0e.png)

**Comment by 1502shivam-singh** [comment]
> @Yiyiyimu @juzhiyuan @nic-chen @gxthrj
> How is it now?
> scrnli_10_04_2021_15-38-50

Some points -
- Avoid using pure black, like you have used in description section. Hurts eyes when using dark mode, when its actually needed i.e. in dark. Try material design based colors
- Don't grey out the CTA's, like the "View on GitHub" button
- Watch out for the other greyed out buttons like the "subscribe" button. The button and button text contrast is quite low.
- Contrast issues elsewhere in the site

image

image

- Something not related to your doing, but some company logos in "Who is using this" section don't have an alpha property, so it looks odd that some have a white background while other don't and they don't mix properly.

Fact is, that the images on the home-page are not yet optimized to fit in a dark mode. Like the design image in description section doesn't look like it belongs to this website in dark mode, because of color differences and all. It even looks as if its cropped out uneven, without any space tbh 😕.

**Comment by iamayushdas** [comment]
> > @Yiyiyimu @juzhiyuan @nic-chen @gxthrj
> 
> > How is it now?
> 
> > [Website change 2](https://user-images.githubusercontent.com/40708551/114266705-4b1b4080-9a15-11eb-9f36-3581053eef0e.png)
> 
> 
> 
> Some points -
> 
> - Avoid using pure black, like you have used in description section. Hurts eyes when using dark mode, when its actually needed i.e. in dark. Try material design based colors
> 
> - Don't grey out the CTA's, like the "View on GitHub" button
> 
> - Watch out for the other greyed out buttons like the "subscribe" button. The button and button text contrast is quite low.
> 
> - Contrast issues elsewhere in the site
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 
> 
> - Something not related to your doing, but some company logos in "Who is using this" section don't have an alpha property, so it looks odd that some have a white background while other don't and they don't mix properly.
> 
> 
> 
> Fact is, that the images on the home-page are not yet optimized to fit in a dark mode. Like the design image in description section doesn't look like it belongs to this website in dark mode, because of color differences and all. It even looks as if its cropped out uneven, without any space tbh 😕.
> 
> 
> 
> 

Okay then will keep your suggestions in mind in next commit

**Comment by iamayushdas** [comment]
@juzhiyuan @Yiyiyimu @1502shivam-singh
After collectively going through all your reviews above

[Website change 3](https://user-images.githubusercontent.com/40708551/114294237-cedb3880-9aba-11eb-8899-75ac4e9b7598.png)

*Note - tried but unable to figure out how to use styled-components for dark mode via customTheme.css (docusaurus way)

**Comment by iamayushdas** [comment]
I am recreating that apisix architecture photo with transparent background. For the better of Dark mode legacy

**Comment by iamayushdas** [comment]
@juzhiyuan @Yiyiyimu @1502shivam-singh  after PR attached to issue no - #301 will be merged
we will get true dark mode compatible image that i have promised to create see :grinning: 
[Website change 4](https://user-images.githubusercontent.com/40708551/114303646-d74c6700-9aec-11eb-919b-5d7aa36725ff.png)

**Comment by 1502shivam-singh** [comment]
> @juzhiyuan @Yiyiyimu @1502shivam-singh
> After collectively going through all your reviews above
> 
> scrnli_11_04_2021_09-51-06
> 
> *Note - tried but unable to figure out how to use styled-components for dark mode via customTheme.css (docusaurus way)

Nice 👍,
Just one last thing, can you fix the text contrast in the download section and the help section.

image

**Comment by iamayushdas** [comment]
> > @juzhiyuan @Yiyiyimu @1502shivam-singh
> 
> > After collectively going through all your reviews above
> 
> > 
> 
> > scrnli_11_04_2021_09-51-06
> 
> > 
> 
> > *Note - tried but unable to figure out how to use styled-components for dark mode via customTheme.css (docusaurus way)
> 
> 
> 
> Nice 👍,
> 
> Just one last thing, can you fix the text contrast in the download section and the help section.
> 
> 
> 
> image
> 
> 
Right now i am figuring out how to deal with that download page styled-components because its not handling in docusaurus way

**Comment by 1502shivam-singh** [comment]
I have got a way to solve your issue, do ask if you are facing any problem.

If I am correct you are facing problem doing this right ? (GIF below, description changing color from black to white)

vid

**Comment by iamayushdas** [comment]
> I have got a way to solve your issue, do ask if you are facing any problem.
> 
> 
> 
> If I am correct you are facing problem doing this right ? (GIF below, description changing color from black to white)
> 
> 
> 
> vid
> 
> 

Yup, i need your help buddy

**Comment by 1502shivam-singh** [comment]
> > I have got a way to solve your issue, do ask if you are facing any problem.
> > If I am correct you are facing problem doing this right ? (GIF below, description changing color from black to white)
> > vid
> 
> Yup, i need your help buddy

The most basic way to do this, that comes to my mind right now is to give the styled components some class and then slide that class property in the customTheme.css with CSS required.

**Comment by iamayushdas** [comment]
> > > I have got a way to solve your issue, do ask if you are facing any problem.
> > > If I am correct you are facing problem doing this right ? (GIF below, description changing color from black to white)
> > > vid
> > 
> > 
> > Yup, i need your help buddy
> 
> The most basic way to do this, that comes to my mind right now is to give the styled components some class and then slide that class property in the customTheme.css with CSS required.

i have given it a try, but  didn't worked. lemme do it again thanks bud

**Comment by 1502shivam-singh** [comment]
> > > > I have got a way to solve your issue, do ask if you are facing any problem.
> > > > If I am correct you are facing problem doing this right ? (GIF below, description changing color from black to white)
> > > > vid
> > > 
> > > 
> > > Yup, i need your help buddy
> > 
> > 
> > The most basic way to do this, that comes to my mind right now is to give the styled components some class and then slide that class property in the customTheme.css with CSS required.
> 
> i have given it a try, but didn't worked. lemme do it again thanks bud

That's how I did it 😂, how's it not working, check again 🙂

**Comment by iamayushdas** [comment]
> > > > > I have got a way to solve your issue, do ask if you are facing any problem.
> 
> > > > > If I am correct you are facing problem doing this right ? (GIF below, description changing color from black to white)
> 
> > > > > vid
> 
> > > > 
> 
> > > > 
> 
> > > > Yup, i need your help buddy
> 
> > > 
> 
> > > 
> 
> > > The most basic way to do this, that comes to my mind right now is to give the styled components some class and then slide that class property in the customTheme.css with CSS required.
> 
> > 
> 
> > i have given it a try, but didn't worked. lemme do it again thanks bud
> 
> 
> 
> That's how I did it 😂, how's it not working, check again 🙂

Yep yep😃

**Comment by iamayushdas** [comment]
@juzhiyuan @Yiyiyimu @nic-chen @liuxiran 
Completed darkmode for apisix-website :relieved: 
here are the changes: (screeshots)

 [Help page](https://user-images.githubusercontent.com/40708551/114376504-4edccd80-9ba3-11eb-8907-b0d9af090aef.png)
 [Team page](https://user-images.githubusercontent.com/40708551/114376510-500dfa80-9ba3-11eb-9800-801220336b72.png)
 [Downloads page](https://user-images.githubusercontent.com/40708551/114376515-513f2780-9ba3-11eb-9317-169bfb1c6397.png)
 [Doc page](https://user-images.githubusercontent.com/40708551/114376491-4c7a7380-9ba3-11eb-90a3-aace4161a36d.png)

Waiting eagerly to gift Dark mode to users and devs

**Review by Yiyiyimu — APPROVED** [review]
Looks amazing! Thanks for the contribution!!

**Comment by Yiyiyimu** [comment]
> Something not related to your doing, but some company logos in "Who is using this" section don't have an alpha property, so it looks odd that some have a white background while other don't and they don't mix properly.

Would fix in #303 cc @1502shivam-singh

**Comment by iamayushdas** [comment]
> > Something not related to your doing, but some company logos in "Who is using this" section don't have an alpha property, so it looks odd that some have a white background while other don't and they don't mix properly.
> 
> 
> 
> Would fix in #303 cc @1502shivam-singh

I was just doing that😞 btw Thanks @Yiyiyimu for this🙂

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
