### PR TITLE
Updated Blog list page's style

### LINKED ISSUE #677: Update Blog list page's style
**Actual Behaviour**

Hi, we have some feedbacks from users that, the website's default Red theme is hard to visit, here has 2 things to improve:

- [ ] Use a better font color, like #000000?
- [ ] Use an appropriate font size, current one is too big;
- [ ] Have a better sidebar to show all posts, see https://reactnative.dev/blog

**Expected Behaviour**

 

**Steps to reproduce it**

Visit https://apisix.apache.org/blog

**Screenshots of the issue**

image

### PR DESCRIPTION
**Pull request by BeeBombshell**
Fixes: #677 

Changes:

- [x]  Used a better font color
- [x]  Used appropriate font size
- [x]  Better sidebar to show all posts

Screenshots of the change:

image

### CODE REVIEW

**Comment by juzhiyuan** [comment]
cc @yzeng25 to have a review 😉

**Comment by yzeng25** [comment]
Hi @BeeBombshell ,

Could you check the online preview link provided by netlify comment above? When I click in to see the preview, the website's format is completely tweaked. Some changes may look good when you run it locally, but it does not show up as expected in the preview.

**Comment by BeeBombshell** [comment]
@yzeng25 The Netlify preview deployment has a staggering view but I can't seem to find a fix. What do I refer to?

Possible Problems:
* customTheme.css file is not loaded
* There is something wrong with my Docusaurus configuration.

I tried fixing both of these but no luck. Would appreciate the help.

**Comment by juzhiyuan** [comment]
Hi @yzeng25, due to jsDelivr limitation, the CSS loading failed 🤔 Could you please run locally to have a check?

**Comment by yzeng25** [comment]
> Hi @yzeng25, due to jsDelivr limitation, the CSS loading failed 🤔 Could you please run locally to have a check?

LGTM.

Cool. I copied the CSS file down and ran it locally. Everything works out fine in both languages. Please continue the merging process.

Thanks @BeeBombshell 👍 
cc @juzhiyuan

**Review by yzeng25 — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
