### PR TITLE
feat: added company who uses Apache APISIX logo

### PR DESCRIPTION
**Pull request by guoqqqi**
Fixes: #[Add issue number here]

Changes:

added company who uses Apache APISIX logo

Screenshots of the change:

### CODE REVIEW

**Comment by guoqqqi** [comment]
image

**Comment by iamayushdas** [comment]
Nice

**Comment by guoqqqi** [comment]
- 思必驰信息科技股份有限公司
- 浙江大东鞋业有限公司
- 上海合合信息科技股份有限公司

The above logo is white and needs to be replaced

The logo that can be added has been added, the rest of the CC @iamayushdas

**Comment by iamayushdas** [comment]
> - 思必驰信息科技股份有限公司
> 
> - 浙江大东鞋业有限公司
> 
> - 上海合合信息科技股份有限公司
> 
> 
> 
> The above logo is white and needs to be replaced
> 
> 
> 
> The logo that can be added has been added, the rest of the CC @iamayushdas  

Okay

**Review by iamayushdas — APPROVED** [review]
LGTM

**Comment by moonming** [comment]
will also update apisix's readme?

**Comment by iamayushdas** [comment]
> will also update apisix's readme?

I will be adding to readme company wall after putting the missing icons.

**Comment by Yiyiyimu** [comment]
@guoqqqi suggest to remove `zihao` and `zhi20` due to https://github.com/apache/apisix-website/pull/376#issuecomment-866279217
> 1. Remove [`zhi20`](http://www.zhi20.com/) due to [suspected pyramid scheme](https://www.163.com/dy/article/G6JJGB4G0534JSFW.html)
> 2. Remove [`zihaowangluo`](http://sms.gs/) since it's an outsourcing company

Also we need to turn the white background to transparency (add alpha channel) to make it compatible with night mode

**Review by iamayushdas — APPROVED** [review]

**Review by Yiyiyimu — CHANGES_REQUESTED** [review]
Need to add alpha channel to make background transparency to be compatible with dark mode

**Review by KishaniKandasamy — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
cc @guoqqqi do you have some progress on this

**Comment by Yiyiyimu** [comment]
> suggest to remove `zihao` and `zhi20` due to [#376 (comment)](https://github.com/apache/apisix-website/pull/376#issuecomment-866279217)
> 
> > 1. Remove [`zhi20`](http://www.zhi20.com/) due to [suspected pyramid scheme](https://www.163.com/dy/article/G6JJGB4G0534JSFW.html)
> > 2. Remove [`zihaowangluo`](http://sms.gs/) since it's an outsourcing company

Hi @guoqqqi do you mind fix this problem

**Review by iamayushdas — APPROVED** [review]

**Comment by guoqqqi** [comment]
> Hi @guoqqqi do you mind fix this problem

@Yiyiyimu Hi, I have removed them in this PR

**Comment by Yiyiyimu** [comment]
@guoqqqi it seems icon of zhi20 haven't been removed yet

**Comment by guoqqqi** [comment]
image
@Yiyiyimu It has been removed

**Review by Yiyiyimu — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
