### PR TITLE
refactor：load images from CDN

### PR DESCRIPTION
**Pull request by Ylikj**
In order to load the picture from the CDN, i modified the files of blog and index.js , is there something wrong？
Is there anything else missing?

### CODE REVIEW

**Comment by guoqqqi** [comment]
image

**Comment by guoqqqi** [comment]
Hi, @Ylikj  If the PR has been completed, please mark it as ready for review

**Comment by yzeng25** [comment]
> In order to load the picture from the CDN, i modified the files of blog and index.js , is there something wrong？ Is there anything else missing?

Hi @Ylikj ,

Sorry for the confusion. I did not specify which kind of images should be changed. It is a bit late but here is the clarification:

For the `authorImageURL` part, you can just leave it as it is. If you really want to change them to CDN, please change them at the very end of this process.

For images in the content of blogs, please change all of them to CDN. 

And here is my suggested plan:

Changing all images is indeed a long process. 

I would suggest split them in multiple pull requests, and categorize them by months . For example, you can create a pull request with images changes for blogs posted in December 2020, and create another pull request with images changes for blogs posted in January 2021. In this way, it is easier for reviewers to do their jobs.

You can get start changing them from `website/blog/2020/12/~` and `website/i18n/zh/docusaurus-plugin-content-blog/2020/12`, which is the earliest blogs we have on our website. Then you can go from there, continue to `/blog/2021/01/~` and `website/i18n/zh/docusaurus-plugin-content-blog/2021/01`.

If you encounter any translation issues, you can also leave them there. Changing the images is enough. We will take care of translations later.

As you may notice, we started to use CDN around July, 2021. So the images involved in each month may come to a peak in `/blog/2021/06/~` or `/blog/2021/07/~`, then suddenly drop a lot because of the change.

Hope this clarifies your confusion, and thank you for your contribution.

**Comment by Ylikj** [comment]
@yzeng25  thanks,I will make changes as required

**Comment by yzeng25** [comment]
> @yzeng25 thanks,I will make changes as required

Alright cool, take your time, there is no rush :)

**Comment by yzeng25** [comment]
Hi @Ylikj , are you still working on this issue? It has been some days since last time, did you encounter any difficulties during the process?

**Comment by Ylikj** [comment]
sorry ,it's done, I will upload it before tomorrow @yzeng25

**Comment by Ylikj** [comment]
hi，may it is not be good -> " split them in multiple pull requests, and categorize them by months ."
because there  are more than twenty ,and they all be closed today . I will  re-upload the modified file in one pr tomorrow ，of course, I will upload by month, not all at once。
If you have other ideas, please @Ylikj 😊,and sorry to disturb you late at night😢 @yzeng25

**Comment by juzhiyuan** [comment]
resolved by https://github.com/apache/apisix-website/pull/810

**Pull request closed without merging**
