### PR TITLE
feat: add issue forms

### LINKED ISSUE #890: Create issue templates/forms
**Actual Behaviour**

 

There are no issue templates or forms to guide a contributor in creating an issue.

**Expected Behaviour**

 

1. Create appropriate issue templates/forms.
2. We could have different templates for updating the site, creating blog posts, updating/issues in documentation and general site updates (other suggestions?).

Adding these templates would make the contributing process streamlined.

**Would you like to work on the issue?**

 

Yes, I would like to work on this issue. Please assign this issue to me.

### PR DESCRIPTION
**Pull request by pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

Fixes: #890 

Changes:

Added issue templates for "Documentation Issue" and "Website Issue".

Screenshots of the change:

Screenshot 2022-02-19 at 7 07 57 PM

Screenshot 2022-02-19 at 7 08 10 PM

Screenshot 2022-02-19 at 7 08 22 PM

### CODE REVIEW

**Comment by bzp2010** [comment]
Great step, maybe the content still needs to be tweaked, so let other contributors to take a look.

ping @juzhiyuan @Baoyuantop @guoqqqi

**Comment by pottekkat** [comment]
@bzp2010 Yes. Sure.

**Comment by Baoyuantop** [comment]
Hi @navendu-pottekkat, thanks. This is very friendly to other contributors, but the categories may need a little more consideration. For example, whether to consider `feat`、`bug`、`discuss`.

**Comment by pottekkat** [comment]
Yes. That was indeed my plan after this PR. We should consolidate the labels across all repos and make it semantic.

For example,

area/docs and area/website
issue/invalid and issue/duplicate etc

I will open up a new issue in the APISIX repo and create a document to track this and to arrive at a decision.

But meanwhile, we can merge this PR to have a template for now and later edit the labels once we have them.

What do you think @Baoyuantop  ?

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Review by guoqqqi — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]
LGTM

**Comment by yzeng25** [comment]
Just out of curiosity, I have a couple questions:
1. Do we need an original blank issue page for fallback? For example, if none of the templates fits an issue, but I still want to raise that issue via GitHub, how is that supposed to work?
2. How to categorize the existing issues by this PR (and potentially next PRs)? Or maybe we can leave them as they are right now?

**Comment by juzhiyuan** [comment]
> Do we need an original blank issue page for fallback? For example, if none of the templates fits an issue, but I still want to raise that issue via GitHub, how is that supposed to work?

Hi @yzeng25, please have a check on the screenshot 😄 It has an Open a blank issue link.

> How to categorize the existing issues by this PR (and potentially next PRs)? Or maybe we can leave them as they are right now?

I agree to leave them as right now.

**Comment by yzeng25** [comment]
> > Do we need an original blank issue page for fallback? For example, if none of the templates fits an issue, but I still want to raise that issue via GitHub, how is that supposed to work?
> 
> Hi @yzeng25, please have a check on the screenshot 😄 It has an Open a blank issue link.
> 
> > How to categorize the existing issues by this PR (and potentially next PRs)? Or maybe we can leave them as they are right now?
> 
> I agree to leave them as right now.

Oh OK, that's great. I thought deleting `.github/issue_template.md` would result in no fallback option. Thanks for clarification.

Then LGTM.

**Review by yzeng25 — APPROVED** [review]

**Comment by pottekkat** [comment]
Thanks all. As discussed, I will open up an issue and start a discussion to consolidate what labels we will use across Apache APISIX repos.

**Pull request merged**
