### PR TITLE
feat: separate Zh blogs

### LINKED ISSUE #623: About the i18n of blogs
**Actual Behaviour**

Currently, our blogs are mixed in English and Chinese. All blogs are displayed whether in English or Chinese. This often brings confusion and inconvenience to users of different languages.

**Expected Behaviour**

When the current environment is in English, only English blogs are displayed, and in the Chinese environment, only Chinese blogs are displayed.

After analysis, we can use the [`draft`](https://docusaurus.io/zh-CN/docs/api/plugins/@docusaurus/plugin-content-blog#markdown-frontmatter) property of the markdown file to solve, It means that the current document is still in draft and will not be displayed in the blog.

So because we default to the English environment, add the `draft` property to all Chinese blogs in the `website/blog` directory.

After that, copy all the blog files to the `website/i18n/zh/docusaurus-plugin-content-blog` directory, and then add the `draft` property to all English blogs.

**Note**: draft will still be displayed in development mode, but after build, it works ~

What do you think？

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Fixes: #623 

Changes:

Created i18n/zh/docusaurus-plugin-content-blog directory and copy all blogs there.

marked all chinese blogs in website/blog as draft.

marked all the English blogs as draft in the i18n/zh/docusaurus-plugin-content-blog directory 

@juzhiyuan @Baoyuantop @liuxiran  @bzp2010

### CODE REVIEW

**Comment by Baoyuantop** [comment]
Hi, thank you very much. Can you successfully build on your local? It looks like there are some pictures with the wrong path due to changes in files location.

**Comment by KishaniKandasamy** [comment]
> Hi, thank you very much. Can you successfully build on your local? It looks like there are some pictures with the wrong path due to changes in files location.

Hi @Baoyuantop ,I think Broken images have been fixed now.
But  Blog content  remains same in my dev environment that **/blog** shows chinese blogs too :(
img

**Comment by Baoyuantop** [comment]
let me check

**Comment by KishaniKandasamy** [comment]
> let me check

Yes

**Comment by Baoyuantop** [comment]
There is one problem you need to pay attention to: draft will still be displayed in development mode, but after build, it works ~

So you need `yarn build` and use some tool like [`serve`](https://www.npmjs.com/package/serve) host the build folder.

Then you can see the correct preview.

**Comment by KishaniKandasamy** [comment]
> There is one problem you need to pay attention to: draft will still be displayed in development mode, but after build, it works ~
> 
> So you need `yarn build` and use some tool like [`serve`](https://www.npmjs.com/package/serve) host the build folder.

yes.I think now it is fixed

**Review by Baoyuantop — APPROVED** [review]

**Comment by KishaniKandasamy** [comment]
@juzhiyuan @liuxiran @bzp2010 @Yiyiyimu @guoqqqi  Please have a look when you are available

**Comment by liuxiran** [comment]
Hi @KishaniKandasamy , may I ask what does `draft` mean? since you have move the Chinese blog to extra folder, why still need to add draft to the original blog? thanks a lot

**Comment by KishaniKandasamy** [comment]
> > Hi @KishaniKandasamy , may I ask what does `draft` mean? since you have move the Chinese blog to extra folder, why still need to add draft to the original blog? thanks a lot
> 
> Hi @liuxiran , I think this [comment](https://github.com/apache/apisix-website/pull/626#issuecomment-928718521) will clear it out :)

If we add draft property to a blog ,It won't be published(Marked as in progress) .So we could avoid chinese blogs displaying   in /blog directory and the other way round(English blogs displaying in /i18n/zh/docusaurus-plugin-content-blog) until we are completely done the translation of these blogs.

**Comment by liuxiran** [comment]
> > > Hi @KishaniKandasamy , may I ask what does `draft` mean? since you have move the Chinese blog to extra folder, why still need to add draft to the original blog? thanks a lot
> > 
> > 
> > Hi @liuxiran , I think this [comment](https://github.com/apache/apisix-website/pull/626#issuecomment-928718521) will clear it out :)
> 
> If we add draft property to a blog ,It won't be published(Marked as in progress) .So we could avoid chinese blogs displaying in /blog directory and the other way round(English blogs displaying in /i18n/zh/docusaurus-plugin-content-blog) until we are completely done the translation of these blogs.

Thanks for your explanation @KishaniKandasamy , so when we published a blog only in Chinese(or English) now, we need to add the other as a draft (this will be a flag to tip that this blog need I18n), am I right? if so, It is a very thoughtful consideration, and it would be better to add a note for those who submit blogs later , e.g. in readme or a new note in https://github.com/apache/apisix-website/tree/master/website/docs/general, we can add it later after this pr merged ^_^

**Review by liuxiran — APPROVED** [review]

**Comment by KishaniKandasamy** [comment]
> > > > Hi @KishaniKandasamy , may I ask what does `draft` mean? since you have move the Chinese blog to extra folder, why still need to add draft to the original blog? thanks a lot
> > > 
> > > 
> > > Hi @liuxiran , I think this [comment](https://github.com/apache/apisix-website/pull/626#issuecomment-928718521) will clear it out :)
> > 
> > 
> > If we add draft property to a blog ,It won't be published(Marked as in progress) .So we could avoid chinese blogs displaying in /blog directory and the other way round(English blogs displaying in /i18n/zh/docusaurus-plugin-content-blog) until we are completely done the translation of these blogs.
> 
> Thanks for your explanation @KishaniKandasamy , so when we published a blog only in Chinese(or English) now, we need to add the other as a draft (this will be a flag to tip that this blog need I18n), am I right? if so, It is a very thoughtful consideration, and it would be better to add a note for those who submit blogs later , e.g. in readme or a new note in https://github.com/apache/apisix-website/tree/master/website/docs/general, we can add it later after this pr merged ^_^

Yes.You are right @liuxiran . It is  important to remind this draft property to those who  work with the blogs :)

**Review by guoqqqi — APPROVED** [review]

**Review by iamayushdas — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
It works! And I just noticed that there have some latest articles which don't have a specific attribute, please take a look and have an update :)

cc @KishaniKandasamy @guoqqqi

**Pull request merged**
